language: node_js
node_js:
  - '0.10'
  - '0.12'
before_install:
  - 'npm install codeclimate-test-reporter -g && npm install -g coveralls'
after_script:
  - 'npm run gen-coverage && cat coverage/lcov.info | coveralls'
